### ISSUE TITLE
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by Kirri777** [FLUORESCENTXX/NetflixAccountGenerator#2]
Hi, I have problem, after run your program and click Generate Account, on cmd returned:

Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "main.py", line 61, in generateNetflixAccount
    result = requests.post(url, headers=headers, data=post_data).json()
  File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "C:\Users\******\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by FLUORESCENTXX** [comment]
Did u install the requirements?

**Comment by Kirri777** [comment]
Yes.
When I change the country via VPN to "de" I don't have this error, but the program does not return anything for 30 minutes, so I turned it off

**Comment by aneeq-ur-rehman4** [comment]
Same Error
